# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Apps\DEV\PROJECTS\KoHighlights\gui_filter.ui'
#
# Created: Thu Apr  6 23:38:59 2023
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_Filter(object):
    def setupUi(self, Filter):
        Filter.setObjectName("Filter")
        Filter.resize(215, 66)
        Filter.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(Filter)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filter_frm1 = QtWidgets.QFrame(Filter)
        self.filter_frm1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frm1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frm1.setObjectName("filter_frm1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.filter_frm1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.filter_txt = QtWidgets.QLineEdit(self.filter_frm1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_txt.sizePolicy().hasHeightForWidth())
        self.filter_txt.setSizePolicy(sizePolicy)
        self.filter_txt.setText("")
        self.filter_txt.setObjectName("filter_txt")
        self.horizontalLayout_4.addWidget(self.filter_txt)
        self.filter_btn = QtWidgets.QPushButton(self.filter_frm1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_btn.sizePolicy().hasHeightForWidth())
        self.filter_btn.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/stuff/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filter_btn.setIcon(icon)
        self.filter_btn.setObjectName("filter_btn")
        self.horizontalLayout_4.addWidget(self.filter_btn)
        self.verticalLayout.addWidget(self.filter_frm1)
        self.filter_frm2 = QtWidgets.QFrame(Filter)
        self.filter_frm2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frm2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frm2.setObjectName("filter_frm2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.filter_frm2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filter_box = QtWidgets.QComboBox(self.filter_frm2)
        self.filter_box.setObjectName("filter_box")
        self.filter_box.addItem("")
        self.filter_box.addItem("")
        self.filter_box.addItem("")
        self.filter_box.addItem("")
        self.horizontalLayout.addWidget(self.filter_box)
        self.filtered_lbl = QtWidgets.QLabel(self.filter_frm2)
        self.filtered_lbl.setText("")
        self.filtered_lbl.setObjectName("filtered_lbl")
        self.horizontalLayout.addWidget(self.filtered_lbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.clear_filter_btn = QtWidgets.QPushButton(self.filter_frm2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_filter_btn.sizePolicy().hasHeightForWidth())
        self.clear_filter_btn.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/stuff/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_filter_btn.setIcon(icon1)
        self.clear_filter_btn.setObjectName("clear_filter_btn")
        self.horizontalLayout.addWidget(self.clear_filter_btn)
        self.verticalLayout.addWidget(self.filter_frm2)

        self.retranslateUi(Filter)
        self.filter_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Filter)

    def retranslateUi(self, Filter):
        self.filter_txt.setToolTip(QtCore.QCoreApplication.translate("Filter", "Type the keywords to filter the visible items", None))
        self.filter_txt.setPlaceholderText(QtCore.QCoreApplication.translate("Filter", "Type here to filter...", None))
        self.filter_btn.setToolTip(QtCore.QCoreApplication.translate("Filter", "Set filter", None))
        self.filter_btn.setText(QtCore.QCoreApplication.translate("Filter", "Filter", None))
        self.filter_box.setToolTip(QtCore.QCoreApplication.translate("Filter", "Select where to search for the keywords", None))
        self.filter_box.setItemText(0, QtCore.QCoreApplication.translate("Filter", "Filter All:", None))
        self.filter_box.setItemText(1, QtCore.QCoreApplication.translate("Filter", "Filter Highlights:", None))
        self.filter_box.setItemText(2, QtCore.QCoreApplication.translate("Filter", "Filter Comments:", None))
        self.filter_box.setItemText(3, QtCore.QCoreApplication.translate("Filter", "Filter Book Titles:", None))
        self.clear_filter_btn.setToolTip(QtCore.QCoreApplication.translate("Filter", "Clear the filter field", None))
        self.clear_filter_btn.setStatusTip(QtCore.QCoreApplication.translate("Filter", "Clears the filter field", None))
        self.clear_filter_btn.setText(QtCore.QCoreApplication.translate("Filter", "Clear", None))

import images_rc
